package econet

const GET_COMPONENTS_ON_BUS = "GET_COMPONENTS_ON_BUS"
const GET_VALUES = "GET_VALUES"
const PARAMS_MODIFICATION = "PARAMS_MODIFICATION"

const PARAM_SCHEDULE_ID = "u6630"
const PARAM_SCHEDULE_AUTO = "H1L0"
const PARAM_SCHEDULE_MANUAL = "H0L1"

const PARAM_POWER_LEVEL_ID = "u81"
const PARAM_POWER_LEVEL_1 = "3"
const PARAM_POWER_LEVEL_2 = "4"
const PARAM_POWER_LEVEL_3 = "5"

const PARAM_POWER_ID = "u7074"
const PARAM_POWER_ON = "H1L0"
const PARAM_POWER_OFF = "H0L1"
